/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Demo Scenarios */
        get: operations["demo_scenarios_api_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Demo */
        post: operations["reset_demo_api_demo_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Workflow */
        post: operations["start_workflow_api_workflows_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["get_workflow_api_workflows__workflow_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Message */
        post: operations["add_message_api_workflows__workflow_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/accept-alternative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Alternative */
        post: operations["accept_alternative_api_workflows__workflow_id__accept_alternative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Proposal */
        post: operations["approve_proposal_api_workflows__workflow_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Proposal */
        post: operations["reject_proposal_api_workflows__workflow_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute Checkout */
        post: operations["execute_checkout_api_workflows__workflow_id__checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Workflow */
        post: operations["cancel_workflow_api_workflows__workflow_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_workflows__workflow_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/simulate-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate Status */
        post: operations["simulate_status_api_orders__order_id__simulate_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Items */
        get: operations["list_items_items_get"];
        put?: never;
        /** Create Item */
        post: operations["create_item_items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptAlternativeRequest */
        AcceptAlternativeRequest: {
            /** Accepted */
            accepted: boolean;
            /** Alternativeid */
            alternativeId?: string | null;
        };
        /** AddMessageRequest */
        AddMessageRequest: {
            /** Message */
            message: string;
        };
        /** Alternative */
        Alternative: {
            /** Id */
            id: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "higher_budget" | "later_delivery" | "different_category" | "weaker_return_terms";
            /** Message */
            message: string;
            adjustedConstraints: components["schemas"]["ShoppingConstraints"];
        };
        /** Approval */
        Approval: {
            /** Id */
            id: string;
            /** Workflowid */
            workflowId: string;
            /** Proposalid */
            proposalId: string;
            /** Proposalversion */
            proposalVersion: number;
            /** Proposalhash */
            proposalHash: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /**
             * Actor
             * @default demo_user
             * @constant
             */
            actor: "demo_user";
            /**
             * Decidedat
             * Format: date-time
             */
            decidedAt: string;
            /**
             * Spendingpolicyresult
             * @enum {string}
             */
            spendingPolicyResult: "approval_required_and_granted" | "rejected_by_user";
            /** Auditsummary */
            auditSummary: string;
        };
        /** ApproveProposalRequest */
        ApproveProposalRequest: {
            /** Proposalid */
            proposalId: string;
            /** Proposalversion */
            proposalVersion: number;
            /** Proposalhash */
            proposalHash: string;
            /**
             * Approved
             * @default true
             */
            approved: boolean;
        };
        /** CheckoutAttempt */
        CheckoutAttempt: {
            /** Id */
            id: string;
            /** Workflowid */
            workflowId: string;
            /** Proposalid */
            proposalId: string;
            /** Approvalid */
            approvalId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "succeeded" | "failed";
            /** Failurereason */
            failureReason?: ("missing_approval" | "proposal_mismatch" | "proposal_expired" | "price_changed" | "out_of_stock" | "delivery_changed" | "return_policy_changed" | "payment_failed") | null;
            /** Paymentauthorizationid */
            paymentAuthorizationId?: string | null;
            /** Merchantorderref */
            merchantOrderRef?: string | null;
            receipt?: components["schemas"]["Receipt"] | null;
        };
        /** CheckoutProposal */
        CheckoutProposal: {
            /** Id */
            id: string;
            /** Workflowid */
            workflowId: string;
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "approved" | "rejected" | "expired" | "checked_out";
            /** Offerid */
            offerId: string;
            /** Merchantname */
            merchantName: string;
            /** Title */
            title: string;
            /**
             * Quantity
             * @default 1
             * @constant
             */
            quantity: 1;
            /** Lineitems */
            lineItems: components["schemas"]["ProposalLineItem"][];
            subtotal: components["schemas"]["Money"];
            taxesAndFees: components["schemas"]["Money"];
            total: components["schemas"]["Money"];
            delivery: components["schemas"]["ProposalDelivery"];
            returns: components["schemas"]["Returns"];
            warranty: components["schemas"]["Warranty"];
            /** Paymentmethodlabel */
            paymentMethodLabel: string;
            /** Approvaltext */
            approvalText: string;
            /**
             * Expiresat
             * Format: date-time
             */
            expiresAt: string;
            /** Hash */
            hash: string;
        };
        /** CheckoutRequest */
        CheckoutRequest: {
            /** Approvalid */
            approvalId: string;
        };
        /** ClarificationQuestion */
        ClarificationQuestion: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Expectedfield */
            expectedField: string;
            /** Examples */
            examples: string[];
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Id */
            id: string;
            /** Bestofferid */
            bestOfferId: string | null;
            /** Confidence */
            confidence: number;
            /**
             * Recommendation
             * @enum {string}
             */
            recommendation: "proceed" | "ask_user" | "stop";
            /** Summary */
            summary: string;
            /** Rankedoffers */
            rankedOffers: components["schemas"]["RankedOffer"][];
            /** Missingevidence */
            missingEvidence?: string[];
        };
        /** DomainEvent */
        DomainEvent: {
            /** Id */
            id: string;
            /** Workflowid */
            workflowId: string;
            /** Type */
            type: string;
            /**
             * Actor
             * @enum {string}
             */
            actor: "user" | "system" | "module";
            /**
             * Module
             * @enum {string}
             */
            module: "orchestrator" | "intent" | "profile" | "catalog" | "comparison" | "proposal" | "consent" | "checkout" | "tracking";
            /** Summary */
            summary: string;
            /** Data */
            data?: Record<string, never>;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** EventsResponse */
        EventsResponse: {
            /** Workflowid */
            workflowId: string;
            /** Events */
            events: components["schemas"]["DomainEvent"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Item */
        Item: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ItemCreate */
        ItemCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** Money */
        Money: {
            /** Amount */
            amount: number;
            /**
             * Currency
             * @default PLN
             * @constant
             */
            currency: "PLN";
        };
        /** Order */
        Order: {
            /** Id */
            id: string;
            /** Workflowid */
            workflowId: string;
            /** Merchantorderref */
            merchantOrderRef: string;
            /**
             * Status
             * @enum {string}
             */
            status: "order_created" | "confirmed" | "packed" | "shipped" | "out_for_delivery" | "delivered" | "exception" | "cancelled" | "return_requested" | "returned";
            /** Title */
            title: string;
            total: components["schemas"]["Money"];
            /** Deliverylabel */
            deliveryLabel: string;
            /** Trackingnumber */
            trackingNumber?: string | null;
            /** Timeline */
            timeline: components["schemas"]["OrderTimelineEntry"][];
        };
        /** OrderTimelineEntry */
        OrderTimelineEntry: {
            /**
             * Status
             * @enum {string}
             */
            status: "order_created" | "confirmed" | "packed" | "shipped" | "out_for_delivery" | "delivered" | "exception" | "cancelled" | "return_requested" | "returned";
            /** Label */
            label: string;
            /**
             * Happenedat
             * Format: date-time
             */
            happenedAt: string;
        };
        /** PolicyBlock */
        PolicyBlock: {
            /**
             * Code
             * @enum {string}
             */
            code: "restricted_product" | "requires_professional_verification" | "unsafe_or_illegal" | "unsupported_request";
            /** Message */
            message: string;
            /** Cansuggestsaferalternative */
            canSuggestSaferAlternative: boolean;
        };
        /** ProposalDelivery */
        ProposalDelivery: {
            /** Label */
            label: string;
            /** Earliest */
            earliest: string;
            /** Latest */
            latest: string;
        };
        /** ProposalLineItem */
        ProposalLineItem: {
            /** Label */
            label: string;
            amount: components["schemas"]["Money"];
        };
        /** RankedOffer */
        RankedOffer: {
            /** Offerid */
            offerId: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Title */
            title: string;
            total: components["schemas"]["Money"];
            /** Reasons */
            reasons: string[];
            /** Tradeoffs */
            tradeoffs: string[];
            /** Disqualifiers */
            disqualifiers: string[];
        };
        /** Receipt */
        Receipt: {
            /** Receiptid */
            receiptId: string;
            total: components["schemas"]["Money"];
            /**
             * Paidat
             * Format: date-time
             */
            paidAt: string;
        };
        /** RejectProposalRequest */
        RejectProposalRequest: {
            /** Proposalid */
            proposalId: string;
            /** Reason */
            reason?: string | null;
        };
        /** Returns */
        Returns: {
            /** Returnable */
            returnable: boolean;
            /** Days */
            days: number;
            /** Label */
            label: string;
        };
        /** ShoppingConstraints */
        ShoppingConstraints: {
            /** Productcategory */
            productCategory: string | null;
            /** Query */
            query: string;
            budgetMax?: components["schemas"]["Money"] | null;
            /** Deliverydeadline */
            deliveryDeadline?: ("today" | "tomorrow" | "this_week") | null;
            /** Compatibility */
            compatibility?: string[];
            /** Musthave */
            mustHave?: string[];
            /** Nicetohave */
            niceToHave?: string[];
            /** Requiredreturndays */
            requiredReturnDays?: number | null;
            /** Forbidden */
            forbidden?: string[];
        };
        /** SimulateStatusRequest */
        SimulateStatusRequest: {
            /**
             * Status
             * @enum {string}
             */
            status: "order_created" | "confirmed" | "packed" | "shipped" | "out_for_delivery" | "delivered" | "exception" | "cancelled" | "return_requested" | "returned";
        };
        /** StartWorkflowRequest */
        StartWorkflowRequest: {
            /** Prompt */
            prompt: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Warranty */
        Warranty: {
            /** Months */
            months: number;
            /** Label */
            label: string;
        };
        /** WorkflowSummary */
        WorkflowSummary: {
            /** Id */
            id: string;
            /**
             * Userid
             * @constant
             */
            userId: "demo_user";
            /**
             * State
             * @enum {string}
             */
            state: "created" | "needs_clarification" | "blocked_by_policy" | "researching" | "no_exact_match" | "awaiting_alternative_acceptance" | "comparing" | "proposal_ready" | "awaiting_approval" | "rejected" | "checkout_in_progress" | "checkout_failed" | "ordered" | "tracking" | "completed" | "cancelled";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Prompt */
            prompt: string;
            /** Summary */
            summary: string;
            /** Availableactions */
            availableActions: ("reply_to_clarification" | "accept_alternative" | "reject_alternative" | "approve_proposal" | "reject_proposal" | "execute_checkout" | "simulate_tracking" | "cancel")[];
        };
        /** WorkflowView */
        WorkflowView: {
            workflow: components["schemas"]["WorkflowSummary"];
            clarification?: components["schemas"]["ClarificationQuestion"] | null;
            guardrail?: components["schemas"]["PolicyBlock"] | null;
            constraints?: components["schemas"]["ShoppingConstraints"] | null;
            /** Alternatives */
            alternatives?: components["schemas"]["Alternative"][] | null;
            comparison?: components["schemas"]["ComparisonResult"] | null;
            proposal?: components["schemas"]["CheckoutProposal"] | null;
            approval?: components["schemas"]["Approval"] | null;
            checkout?: components["schemas"]["CheckoutAttempt"] | null;
            order?: components["schemas"]["Order"] | null;
            /** Events */
            events: components["schemas"]["DomainEvent"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    demo_scenarios_api_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reset_demo_api_demo_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    start_workflow_api_workflows_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartWorkflowRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_api_workflows__workflow_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_api_workflows__workflow_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_alternative_api_workflows__workflow_id__accept_alternative_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptAlternativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_workflows__workflow_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_workflows__workflow_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectProposalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_checkout_api_workflows__workflow_id__checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_workflow_api_workflows__workflow_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_events_api_workflows__workflow_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_status_api_orders__order_id__simulate_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateStatusRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_items_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
        };
    };
    create_item_items_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
